### ISSUE TITLE
Allow for log scale of the y axis

### ISSUE THREAD

**Issue by rossb34** [joshuaulrich/xts#103]
Allow for log scale of the y axis. This is supported by `base::plot` and `PerformanceAnalytics::Chart.TimeSeries` so we should support it in `plot.xts` as well. Thanks to Gei Lin for the feature request via  [R-SIG-Finance](https://stat.ethz.ch/pipermail/r-sig-finance/2015q2/013323.html).

**Comment by ethanbsmith** [comment]
just some notes for myself:

1. use `devtools::load_all()` to build and load the package from source w/ namespace and bindings that work for interactive debugging. just modifying and `source()`-ing files runs into a plethora of issues.
2. ultimately, `log='y''` needs to be passed to `plot.window()` from `set_window()`
3. need to modify `scale_ranges()` and the `win` calculations in `set_window()` to not produce unnecessary negative `ylim`. 
4. As an example, this happens quite easily during the `cs$add_frame(0,ylim=c(0,1),asp=0.5)` which sets up the frame for the header. The parameters of this call are intertwined w/ the subsequent `text(xlim[1],0.5,..)` call that actually produces the title.. While the particular frame for the title should not be log scale the negative `ylim` from the title affects subsequent processing
5. there are a few other similar situation 
6. will also need to think about how to handle `multi.panel = TRUE`. initial thought is to apply logy to all panels

**Comment by joshuaulrich** [comment]
We can't simply use `plot.window(..., log = "y")` because the data range may include values <= 0, which means `log()` returns `NaN`. We will need to scale the data so it only has positive values. And that means we will need to adjust the y-axis labels to represent the actual (not the positive-adjusted) values.

Taking the log of a value <= 0 can also be a problem if we add a panel to the plot. We use the xts plot object `asp` values to (re-)set the global/device ylim for each panel in order to put the panels in the correct relative locations on the device. This can create negative global ylim value(s) for one or more of the panels, which will cause `plot.window(..., log = "y")` to error.

So we may need to manually map in/out of log space. Here are some thoughts on what needs to happen if we go that route:

* Scale the raw data so the min is always 1 before taking the log, and map the y-axis labels (based on the raw data) to their respective scaled values
* May have to use `axTicks()` for because `pretty()` does not support log scales
* Test if log needs to be global to the plot, or can be by panel (I think it can be by panel)

**Comment by ethanbsmith** [comment]
dont think the data itself should ever have values <= 0 . neither base nor quantmod plotting currently supports that kind of input. if more talking about negative ranges in the plot area introduced by the `multi.plot > 1`, then i probably reluctantly agree

**Comment by joshuaulrich** [comment]
Hmm, guess that wasn't clear. I'm referring to when the raw data has negative values. And that causes `plot.window(..., log = "y")` to error. So we can't just add `log = "y"` and be done. For example, `plot.window(c(-1, 1), c(-1, 1), log = "y")`
