### ISSUE TITLE
Why sum and mean works different in apply.monthly?

### ISSUE THREAD

**Issue by fcasarramona** [joshuaulrich/xts#124]
When `apply.monthly` in a `xts` multivaluate time series (with more than one column) `apply.monthly(xts.ts, sum)` returns a one column time series but `apply.monthly(xts.ts, mean)` returns the same number of columns of the original. 

Here is an example:

```
library(xts)
xts.ts <- xts(matrix(rnorm(462), nrow = 231),as.Date(13514:13744,origin="1970-01-01"))
dim(xts.ts)
[1] 231   2
dim(apply.monthly(xts.ts, mean))
[1] 8 2
dim(apply.monthly(xts.ts, sum))
[1] 8 1
```

The same is true with other `xts` `apply` functions.

This seems inconsistent.

**Comment by braverock** [comment]
Why not use colMeans and colSums to make sure you get what you think you're getting?

```r
x<-xts(matrix(rnorm(1000),ncol=10),order.by=as.Date(1:100))
mean(x)
sum(x)
apply.weekly(x,sum)
apply.weekly(x,mean)
apply.weekly(x,colSums)
apply.weekly(x,colMeans)
```

**Comment by fcasarramona** [comment]
Thanks, just discovered I can do it with `colSums`.
In this case, `apply.weekly(x,sum)` and `apply.weekly(x,mean)` should return 1 column `xts` both.

**Comment by joshuaulrich** [comment]
The problem is that xts defines `mean.xts` in its namespace and it is being dispatched, even though it is not registered as a S3 method.

`mean.xts` was added when R Core decided that `mean` should not operate by-column for matrices and data.frames.  Seems like it might be a good idea to rename both `mean.xts` and `sd.xts` as `mean_xts` and `sd_xts`, respectively, in order to avoid this inconsistency.

Or maybe they should just be removed all together?  They're not exported, so CRAN likely would not allow their use in other packages.

**Comment by fcasarramona** [comment]
In my opinion is better just remove them and let ```colSums``` and his family functions do the work. This will be consistent with ```matrix```.

**Comment by sushant-choudhary** [comment]
Using colSums takes care of the sum function not being applied by columns, however what would be a similar fix for the sd( ) function, which, like sum( ), is not applied by columns in period.apply.

**Comment by pverspeelt** [comment]
@sushant-choudhary ,

A late answer, but the package matrixStats has all these functions available for columns and rows. Using the example above that would be: 

`apply.weekly(x, matrixStats::colSds)`
