### ISSUE TITLE
lag.xts masked by dplyr

### ISSUE THREAD

**Issue by yilisg** [joshuaulrich/xts#131]
Loading **dplyr** breaks the lag function in a multivariate **xts** object, even when **xts** package is loaded after **dplyr**. Should xts::lag.xts be implemented as xts::lag to avoid confusion (and allow overriding of the lag function masking through the load sequence of packages)? Thanks.

```r
library("xts")
x <- xts(matrix(rnorm(50), 10, 5), Sys.Date()+1:10)
lag(x) # works
````

After loading dplyr,

```r
library("dplyr")
lag(x) # Error in `[.xts`(x, seq_len(xlen - n)) : subscript out of bounds
````

**lag** and not **xts.lag** was used in the xts help page which was slightly confusing,

```r
xts::lag(x) # not found in namespace:xts
lag.xts(x) # works as intended
stats::lag(x) # also works as intended
````

**Comment by joshuaulrich** [comment]
> Should xts::lag.xts be implemented as xts::lag to avoid confusion (and allow overriding of the lag function masking through the load sequence of packages)?

No. `lag` is a S3 generic function defined in the stats package. `xts::lag.xts` is a S3 method for the `stats::lag` generic. Regardless, what you suggest wouldn't fix your issue, because `dplyr::lag` would still mask `xts::lag`.

> lag and not xts.lag [sic] was used in the xts help page which was slightly confusing

That's how S3 methods are documented, so I can't change it.

`dplyr::lag` masks the `stats::lag` generic and breaks method dispatch. This is a known issue with dplyr (see https://github.com/hadley/dplyr/issues/1586 and the comments on https://github.com/hadley/dplyr/commit/f8a46e030b7b899900f2091f41071619d0a46288). Hadley has told others to use `stats::lag` directly if they want to use the S3 generic instead of `dplyr::lag`.

Closing, since this isn't an issue with xts and cannot be fixed by changing anything in xts.

**Comment by yilisg** [comment]
Thank you Josh.
