### ISSUE TITLE
Feature request: columns with different types

### ISSUE THREAD

**Issue by randomgambit** [joshuaulrich/xts#160]
Hello everyone,

First of all, congrats for this wonderful package. After playing with it a bit, it seems to me that one of the biggest limitation of `xts` is that it needs to work with a matrix of data.

In order words, I cannot carry on `character` columns that may contain important information about my time series (say, some group attributes,or sector names or any other non-numeric information).

Is there a way to use `xts` and still keep these columns? Do you plan on developing such a feature?

Many thanks!

**Comment by braverock** [comment]
`xts` does use `matrix` as its internal storage.

An R `matrix` object can only hold __either__ character or numeric data.

We've done some work with xts lists to allow columns of multiple different types, including character and factor.  However, this work is non-trivial, and has languished due to lack of other people (not us) willing to write tests and contribute patches.

**Comment by randomgambit** [comment]
I see.

But could not you have some sort of two step process where `xts` automatically splits the dataframe into two matrices (numeric and non-numeric), computes separately that the users needs to compute, and then recombine the output into one dataframe?
that would be a `dplyr` killer for me.

**Comment by joshuaulrich** [comment]
The `xts` class extends the `zoo` class, and `zoo` is meant to be a replacement for the `stats::ts` class.  Both xts and zoo objects are a matrix with an index attribute, and you cannot have columns with different types in a matrix.  So you cannot keep character columns with numeric columns in xts or zoo objects.

This has been proposed before, and some prototype work has been attempted in [xtsExtra](https://github.com/joshuaulrich/xtsExtra) and in [xtsExtra during Google Summer of Code, 2013](https://github.com/EvilTosha/xts-GSoC13/tree/master/xts/pkg/xtsExtra).  This is not something that will be added to the xts class, however, because it would mean that the xts class could no longer be an extension of the zoo class.

If you want to try the prototype work, I recommend trying the [GSoC 2013](https://github.com/EvilTosha/xts-GSoC13/tree/master/xts/pkg/xtsExtra) version.  I'd appreciate your feedback on it.

**Comment by joshuaulrich** [comment]
> But could not you have some sort of two step process where `xts` automatically splits the dataframe into two matrices (numeric and non-numeric), computes separately that the users needs to compute, and then recombine the output into one dataframe?
that would be a `dplyr` killer for me.

That's what the GSoC-2013 work does.  But to be a "`dplyr` killer", wouldn't you want to be able to aggregate by some of those character columns?  That would require entirely new functions, because `to.period`, `period.apply`, etc wouldn't know about the extra character data.

**Comment by randomgambit** [comment]
well you can find inspiration from `Pandas`. In general, one wants to carry on the `character` information so simple functions like `first` and `last` are the ones to be used for characters. No real fancy stuff here! :)

**Comment by joshuaulrich** [comment]
Lack of inspiration isn't the problem.  The problems are implementation details, and looking at implementations in other languages isn't particularly helpful in solving implementation details in another language.

I don't know what you mean by "carry character information so functions like `first` and `last` are the ones to be used for characters".  You may not think it's "fancy stuff", but computers are extremely pedantic beasts, so they don't respond well to vague commands. ;)

**Comment by randomgambit** [comment]
ok, thanks @joshuaulrich !

**Comment by joshuaulrich** [comment]
Closing, since xts-proper can never have this functionality.  It will exist in another class (possibly another package) when implemented.
