### ISSUE TITLE
Wrong Time series 

### ISSUE THREAD

**Issue by Maryoda2** [joshuaulrich/xts#253]
Hi !

I would like to plot a time series but in fact I'm faced to a problem before plotting.

This is what I get : 

I only have one measurement a day 
I should have measurements every 5 min in my dataset.But instead all my mesurements are at 02:00.

May I have some help, please ?

       Date              Temperature

2018-05-24 02:00:00  3.33
2018-05-24 02:00:00  3.91
2018-05-24 02:00:00  4.47
2018-05-24 02:00:00  5.01
2018-05-24 02:00:00  1.53
2018-05-24 02:00:00  1.67
2018-05-24 02:00:00  1.69
2018-05-24 02:00:00  1.77
2018-05-25 02:00:00  1.47
2018-05-25 02:00:00  1.58
2018-05-25 02:00:00  1.61
2018-05-25 02:00:00  1.72
2018-05-25 02:00:00  1.94
2018-05-25 02:00:00  2.27

SCRIPT :

series = xts(data$Air.Temperature, order.by = data$Sample.Time, tzone = Sys.getenv("TZ"))
series

[test.txt](https://github.com/joshuaulrich/xts/files/2208762/test.txt)

**Comment by joshuaulrich** [comment]
I'm closing your issue because this tracker is for reporting bugs and requesting features, not for general help or support.  From the [contributing guide](https://github.com/joshuaulrich/xts/blob/d1128447c6eae97ded27ecde170f59b32023a0fc/.github/CONTRIBUTING.md):

> ### Have a question?
> 
> Please do not open an issue to ask a question about how to use the package. Instead, ask your question on [Stack Overflow](http://stackoverflow.com/questions/tagged/r) or the [R-SIG-Finance](https://stat.ethz.ch/mailman/listinfo/r-sig-finance) mailing list (you must subscribe to post).

----

That said, I cannot reproduce your issue.

```r
x <- read.table("~/Downloads/test.txt", sep="\t", header=TRUE, as.is=TRUE)
series = xts(x$Air.Temperature, order.by = as.POSIXct(x$Sample.Time, "UTC", "%d.%m.%Y %H:%M"))
head(series)
#                     [,1]
# 2018-05-24 15:00:00 1.90
# 2018-05-24 15:05:00 2.13
# 2018-05-24 15:10:00 2.34
# 2018-05-24 15:15:00 2.21
# 2018-05-24 15:20:00 2.05
# 2018-05-24 15:25:00 1.94
```

It is very important to provide a minimal [reproducible example](https://stackoverflow.com/q/5963269/271616) for people to be able to help you when you post to StackOverflow or R-SIG-Finance.
