### ISSUE TITLE
add more time of day subsetting information to the documentation

### ISSUE THREAD

**Issue by braverock** [joshuaulrich/xts#304]
### Description

Time of day subsetting `['T08:00/T15:00']` has been supported by xts since 2008.

There is one question in the xts FAQ which discusses time of day subsetting, but nothing in the function documentation.

Add this information to the `[.xts` documentation, and add `[.xts` to the seealso for `xts` documentation.

Additional subsetting information could probably be added as well to assist users trying to figure things out.

**Comment by joshuaulrich** [comment]
Great suggestion!  We need to make sure to document the required format `"THH:MM:SS/THH:MM:SS"` with emphasis on the leading `"T"` and leading zero.  We should also make sure that `[.xts` is _linked_ to `xts` in the SeeAlso section.

It might also help to note what currently doesn't work.  For example, subsetting by a single time (`"THH:MM"`), and open-ended intervals (`"/THH:MM"`).  And discuss what happens when the start of the interval is a time greater than the end of the interval (i.e. the behavior [described in this commit](https://github.com/joshuaulrich/xts/commit/c91b676f08903e10a5fb82ad27e74f7a8bd0e40e)).
