### ISSUE TITLE
new print() formatting breaks first/last default behavior

### ISSUE THREAD

**Issue by ethanbsmith** [joshuaulrich/xts#388]
### Description

feature #321 has changed the behavior of `head()` and `tail()` for `n >= 42`. instead of printing exactly n rows, it truncates the output to just a few of the first and last rows, with an `...` in between. This also happens with `first()` and `last()`.

i suspect this affects other output scenarios where explicit subsetting produced more than 42 rows, though not sure how common that use case is. 

### Expected behavior

first and last should print exactly n rows

### Minimal, reproducible example

```r
tail(as.xts(sample_matrix), 45)
```

### Session Info

```r
quantmod_0.4.20.2  TTR_0.24.3.1       xts_0.12.9900      zoo_1.8-11
```

**Comment by joshuaulrich** [comment]
Actually, I don't think this is a bug or unintended behavior. Those functions still work as intended. The "problem" is that the results are auto-printed, which calls `print.xts()` automatically. And 40 is the default number of rows to truncate. There's no easy way for `print.xts()` to know what call immediately preceded it.

The solution will be to set the yet-to-be-named option to a value you prefer. I chose 40 because that's roughly what fits on my laptop screen. data.table uses 100. I'm open to suggestions for the default vaule.

**Comment by ethanbsmith** [comment]
didnt mean to imply it broke these functions directly. just that the effective behavior was different

  *   anecdotal, but ive never run into this  w/ data.table. confirmed it has the same issue w/ `tail(x, 101)`
  *   1080p can show around 55 rows of autput w/ default fonts/size

anything between 55-100 for default would be my suggestion.
________________________________

**Comment by joshuaulrich** [comment]
I bumped the default to 100 and added a global option to control it (in 701f4de28a1ed8165bb7ac89e81a2235fcb49737).
