### ISSUE TITLE
plot.xts - positioning of labels for event lines

### ISSUE THREAD

**Issue by timelyportfolio** [joshuaulrich/xts#83]
I remember back with `xtsExtra` in these [lines](https://github.com/joshuaulrich/xtsExtra/blob/master/R/plot.R#L433-L434) there was a `yadj` and `offset` to help position labels for event lines that I was able to employ in this [post](http://timelyportfolio.blogspot.com/2012/08/plotxts-is-wonderful.html).  Is this an anticipated addition?

**Comment by joshuaulrich** [comment]
We were just discussing this today, because of this question on stackoverflow: [Adjusting event.labels in addEventLines in the new xts (old xtsExtra)](http://stackoverflow.com/q/29784718/271616).  The thought was to allow the user to pass the following arguments to `text` via `...`: `offset`, `srt`, `cex`.  Would those be adequate?

**Comment by timelyportfolio** [comment]
for now I think `offset`, `srt`, and `cex` will be plenty sufficient.  Oh, `family` would be nice for text `pch` also but not necessary.
